import type { EffectBlock, ItemDef, SetDef, UnmodelledReason } from "../engine/model.ts";
import { UNMODELLED_PERKS } from "./attributes.ts";

export interface BlockCounts {
  blocks: number;
  modelledClauses: number;
  unmodelled: Record<UnmodelledReason, number>;
  effects: number;
  formulaEffects: number;
  unverifiedEffects: number;
}

export interface Coverage {
  items: number;
  mythics: number;
  itemsWithModelledEffects: number;
  maxTiers: BlockCounts;
  allTiers: BlockCounts;
  setTiers: BlockCounts;
  enchants: { total: number; modelled: number; unmodelled: Record<UnmodelledReason, number> };
  markdown: string;
}

const REASONS: UnmodelledReason[] = ["not-production", "mechanic", "mythic-random", "unparsed"];
const zero = (): Record<UnmodelledReason, number> => ({ "not-production": 0, mechanic: 0, "mythic-random": 0, unparsed: 0 });

function countBlocks(blocks: EffectBlock[]): BlockCounts {
  const c: BlockCounts = { blocks: blocks.length, modelledClauses: 0, unmodelled: zero(), effects: 0, formulaEffects: 0, unverifiedEffects: 0 };
  for (const b of blocks) {
    c.modelledClauses += new Set([...b.effects.map((e) => e.text), ...b.bonusEnchant.map((x) => x.text)]).size;
    for (const u of b.unmodelled) c.unmodelled[u.reason]++;
    c.effects += b.effects.length + b.bonusEnchant.length;
    c.formulaEffects += b.effects.filter((e) => typeof e.value !== "number").length;
    c.unverifiedEffects += b.effects.filter((e) => !e.source.verified).length + b.bonusEnchant.filter((x) => !x.source.verified).length;
  }
  return c;
}

const maxTier = (i: ItemDef) => i.tiers[i.tiers.length - 1];
const esc = (s: string) => s.replace(/\|/g, "\\|");

function countsRow(label: string, c: BlockCounts): string {
  return `| ${label} | ${c.blocks} | ${c.modelledClauses} | ${REASONS.map((r) => c.unmodelled[r]).join(" | ")} | ${c.effects} | ${c.formulaEffects} | ${c.unverifiedEffects} |`;
}

export function buildCoverage(items: readonly ItemDef[], sets: readonly SetDef[]): Coverage {
  const maxTiers = countBlocks(items.map(maxTier));
  const allTiers = countBlocks(items.flatMap((i) => i.tiers));
  const setTiers = countBlocks(sets.flatMap((s) => s.tiers));
  const enchants = { total: 0, modelled: 0, unmodelled: zero() };
  for (const i of items) {
    if (!i.enchant) continue;
    enchants.total++;
    if (i.enchant.unmodelled) enchants.unmodelled[i.enchant.unmodelled.reason]++;
    else enchants.modelled++;
  }
  const itemsWithModelledEffects = items.filter((i) => i.tiers.some((t) => t.effects.length || t.bonusEnchant.length)).length;

  const lines: string[] = [
    "# Item effect coverage",
    "",
    "Generated by `src/data/coverage.test.ts` from `src/data/generated/items.json` (run `UPDATE_COVERAGE=1 npm test` to refresh).",
    "A clause is one comma- or sentence-separated part of an item, set or enchant text.",
    "\"Modelled\" clauses produce typed effects or bonus enchant levels; the others are kept with a reason.",
    "Unverified effects rely on a reading of the wiki text that the wiki doesn't state outright (each carries a note).",
    "",
    `- Items: ${items.length} (${items.length - items.filter((i) => i.mythic).length} regular, ${items.filter((i) => i.mythic).length} Mythic); ${itemsWithModelledEffects} have at least one modelled effect.`,
    `- Sets: ${sets.length} with ${setTiers.blocks} tiers.`,
    `- Enchants: ${enchants.total}, of which ${enchants.modelled} modelled, ${REASONS.filter((r) => enchants.unmodelled[r]).map((r) => `${enchants.unmodelled[r]} ${r}`).join(", ")}.`,
    "",
    "| Texts | Blocks | Modelled clauses | not-production | mechanic | mythic-random | unparsed | Effects | Formula effects | Unverified effects |",
    "|---|---|---|---|---|---|---|---|---|---|",
    countsRow("Item tiers at max quality", maxTiers),
    countsRow("All item tiers", allTiers),
    countsRow("Set tiers", setTiers),
    "",
  ];

  const unmodelledRows: string[] = [];
  for (const i of items) {
    for (const u of maxTier(i).unmodelled) if (u.reason !== "mythic-random") unmodelledRows.push(`| ${esc(i.name)} | ${u.reason} | ${esc(u.text)} | ${esc(u.note ?? "")} |`);
    if (i.enchant?.unmodelled && i.enchant.unmodelled.reason !== "mythic-random") {
      unmodelledRows.push(`| ${esc(i.name)} (enchant) | ${i.enchant.unmodelled.reason} | ${esc(i.enchant.desc)} | ${esc(i.enchant.unmodelled.note ?? "")} |`);
    }
  }
  for (const s of sets) for (const t of s.tiers) for (const u of t.unmodelled) unmodelledRows.push(`| ${esc(s.name)} (${t.pieces} pieces) | ${u.reason} | ${esc(u.text)} | ${esc(u.note ?? "")} |`);
  lines.push(
    "## Unmodelled clauses (max quality, sets and enchants; Mythic random bonuses omitted)",
    "",
    "| Source | Reason | Clause | Note |",
    "|---|---|---|---|",
    ...unmodelledRows,
    "",
    "## Unmodelled attribute perks",
    "",
    "| Attribute | Points | Perk | Reason |",
    "|---|---|---|---|",
    ...UNMODELLED_PERKS.map((p) => `| ${p.attribute} | ${p.points} | ${esc(p.text)} | ${p.reason} |`),
    "",
  );

  return { items: items.length, mythics: items.filter((i) => i.mythic).length, itemsWithModelledEffects, maxTiers, allTiers, setTiers, enchants, markdown: lines.join("\n") };
}
